apiVersion: chorister.dev/v1alpha1
kind: ChoCluster
metadata:
  labels:
    app.kubernetes.io/name: chorister
    app.kubernetes.io/managed-by: kustomize
  name: chocluster-sample
spec:
  operators:
    kro: "latest"
    stackgres: "latest"
    nats: "latest"
    dragonfly: "latest"
    certManager: "latest"
    gatekeeper: "latest"
  observability:
    monitoringNamespace: cho-monitoring
    retention:
      metrics: "30d"
      logs: "14d"
      traces: "7d"
