apiVersion: chorister.dev/v1alpha1
kind: ChoApplication
metadata:
  labels:
    app.kubernetes.io/name: chorister
    app.kubernetes.io/managed-by: kustomize
  name: choapplication-sample
spec:
  # TODO(user): Add fields here
